### ISSUE TITLE
最新版本报错

### ISSUE THREAD

**Issue by ning0818** [idcsmart/ZJMF-CBAP#26]
宝塔网站日志

＞getPk(＇idcsmart_plugin＇＂ while reading response header from upstream, client: xxxxxxxx, server: xxxxxxxxxx, request: ＂GET / HTTP/1.1＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-72.sock:＂, host: ＂xxxxxxxxxxx＂
2024/04/10 10:11:25 [error] 6682#0: *5646 FastCGI sent in stderr: ＂PHP message: PHP Fatal error: Uncaught think\db\exception\PDOException: SQLSTATE[HY000] [2002] Connection refused in /www/wwwroot/cloud/vendor/topthink/think-orm/src/db/PDOConnection.php:796
Stack trace:
#0 /www/wwwroot/cloud/vendor/topthink/think-orm/src/db/connector/Mysql.php(66): think\db\PDOConnection-＞getPDOStatement(＇SHOW FULL COLUM...＇)
#1 /www/wwwroot/cloud/vendor/topthink/think-orm/src/db/PDOConnection.php(422): think\db\connector\Mysql-＞getFields(＇`idcsmart_plugi...＇)
#2 /www/wwwroot/cloud/vendor/topthink/think-orm/src/db/PDOConnection.php(362): think\db\PDOConnection-＞getTableFieldsInfo(＇idcsmart_plugin＇)
#3 /www/wwwroot/cloud/vendor/topthink/think-orm/src/db/PDOConnection.php(409): think\db\PDOConnection-＞getSchemaInfo(＇idcsmart_plugin＇)
#4 /www/wwwroot/cloud/vendor/topthink/think-orm/src/db/PDOConnection.php(459): think\db\PDOConnection-＞getTableInfo(＇idcsmart_plugin＇, ＇pk＇)
#5 /www/wwwroot/cloud/vendor/topthink/think-orm/src/db/Query.php(291): think\db\PDOConnection-＞getPk(＇idcsmart_plugin＇＂ while reading response header from upstream, client: xxxxxxxxx, server: xxxxxxxxx, request: ＂GET / HTTP/1.1＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-72.sock:＂, host: ＂xxxxxxxx＂

**Comment by wyh-luoyu** [comment]
这个是跑定时任务还是哪点报的错，看你这个是数据库连接错误
