### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by liuyiyangwang** [idcsmart/ZJMF-CBAP#33]
2024-11-12 14:37:00 TASK ERROR [执行报错 php [/usr/share/nginx/html/cron/task.php] exit status 255]
2024-11-12 14:37:00 TASK ERROR [异常结束执行 php [/usr/share/nginx/html/cron/task.php] PHP Fatal error:  Uncaught think\db\exception\PDOException: SQLSTATE[HY000] [2019] Unknown character set in /usr/share/nginx/html/vendor/topthink/think-orm/src/db/PDOConnection.php:796
Stack trace:
#0 /usr/share/nginx/html/vendor/topthink/think-orm/src/db/connector/Mysql.php(66): think\db\PDOConnection->getPDOStatement('SHOW FULL COLUM...')
#1 /usr/share/nginx/html/vendor/topthink/think-orm/src/db/PDOConnection.php(422): think\db\connector\Mysql->getFields('`idcsmart_plugi...')
#2 /usr/share/nginx/html/vendor/topthink/think-orm/src/db/PDOConnection.php(362): think\db\PDOConnection->getTableFieldsInfo('idcsmart_plugin')
#3 /usr/share/nginx/html/vendor/topthink/think-orm/src/db/PDOConnection.php(409): think\db\PDOConnection->getSchemaInfo('idcsmart_plugin')
#4 /usr/share/nginx/html/vendor/topthink/think-orm/src/db/PDOConnection.php(459): think\db\PDOConnection->getTableInfo('idcsmart_plugin', 'pk')
#5 /usr/share/nginx/html/vendor/topthink/think-orm/src/db/Query.php(291): think\db\PDOConnection->getPk('idcsmart_plugin')
#6 /usr/s in /usr/share/nginx/html/vendor/topthink/think-orm/src/db/PDOConnection.php on line 796

**Comment by liuyiyangwang** [comment]
nginx-1          | 2024/11/12 14:40:05 [notice] 1#1: start worker process 35
php_cron_task-1  | 2024-11-12 14:14:00 TASK INFO [开始执行 php [/usr/share/nginx/html/cron/task.php]]
php_cron_task-1  | 2024-11-12 14:14:00 TASK INFO [开始执行 php [/usr/share/nginx/html/cron/task.php]]
php_cron_task-1  | 2024-11-12 14:14:00 TASK ERROR [执行报错 php [/usr/share/nginx/html/cron/task.php] exit status 255]
php_cron_task-1  | 2024-11-12 14:14:00 TASK ERROR [异常结束执行 php [/usr/share/nginx/html/cron/task.php] PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Fatal error:  require(): Failed opening required '/usr/share/nginx/html/cron/../config.php' (include_path='.:/usr/local/lib/php') in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | ]
php_cron_task-1  | 2024-11-12 14:14:00 TASK ERROR [执行报错 php [/usr/share/nginx/html/cron/task.php] exit status 255]
php_cron_task-1  | 2024-11-12 14:14:00 TASK ERROR [异常结束执行 php [/usr/share/nginx/html/cron/task.php] PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Fatal error:  require(): Failed opening required '/usr/share/nginx/html/cron/../config.php' (include_path='.:/usr/local/lib/php') in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | ]
php_cron_task-1  | 2024-11-12 14:24:00 TASK INFO [开始执行 php [/usr/share/nginx/html/cron/task.php]]
php_cron_task-1  | 2024-11-12 14:24:00 TASK INFO [开始执行 php [/usr/share/nginx/html/cron/task.php]]
php_cron_task-1  | 2024-11-12 14:25:00 TASK ERROR [执行报错 php [/usr/share/nginx/html/cron/task.php] exit status 255]
php_cron_task-1  | 2024-11-12 14:25:00 TASK ERROR [异常结束执行 php [/usr/share/nginx/html/cron/task.php] PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Fatal error:  require(): Failed opening required '/usr/share/nginx/html/cron/../config.php' (include_path='.:/usr/local/lib/php') in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | ]
php_cron_task-1  | 2024-11-12 14:25:00 TASK ERROR [执行报错 php [/usr/share/nginx/html/cron/task.php] exit status 255]
php_cron_task-1  | 2024-11-12 14:25:00 TASK ERROR [异常结束执行 php [/usr/share/nginx/html/cron/task.php] PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Fatal error:  require(): Failed opening required '/usr/share/nginx/html/cron/../config.php' (include_path='.:/usr/local/lib/php') in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | ]
php_cron_task-1  | 2024-11-12 14:35:00 TASK INFO [开始执行 php [/usr/share/nginx/html/cron/task.php]]
php_cron_task-1  | 2024-11-12 14:35:00 TASK INFO [开始执行 php [/usr/share/nginx/html/cron/task.php]]
php_cron_task-1  | 2024-11-12 14:35:00 TASK ERROR [执行报错 php [/usr/share/nginx/html/cron/task.php] exit status 255]
php_cron_task-1  | 2024-11-12 14:35:00 TASK ERROR [异常结束执行 php [/usr/share/nginx/html/cron/task.php] PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Fatal error:  require(): Failed opening required '/usr/share/nginx/html/cron/../config.php' (include_path='.:/usr/local/lib/php') in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | ]
php_cron_task-1  | 2024-11-12 14:35:00 TASK ERROR [执行报错 php [/usr/share/nginx/html/cron/task.php] exit status 255]
php_cron_task-1  | 2024-11-12 14:35:00 TASK ERROR [异常结束执行 php [/usr/share/nginx/html/cron/task.php] PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Warning:  require(/usr/share/nginx/html/cron/../config.php): failed to open stream: No such file or directory in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | PHP Fatal error:  require(): Failed opening required '/usr/share/nginx/html/cron/../config.php' (include_path='.:/usr/local/lib/php') in /usr/share/nginx/html/cron/task.php on line 6
php_cron_task-1  | ]

**Comment by liuyiyangwang** [comment]
没有config.php文件

**Comment by liuyiyangwang** [comment]
我将public/install/config.php 复制到 html下吗 就出现了 php 连接不上 db 的报错
